### ISSUE TITLE
Home page https://multipass.run/   ...  issue with second suggested command ?  ...

### ISSUE THREAD

**Issue by allanford17** [canonical-web-and-design/multipass.run#125]
Home page https://multipass.run/

suggests to run command:

multipass exec ubuntu-lts -- lsb_release -a

but this gives me result as per:

C:\Users\allan>multipass exec ubuntu-lts -- lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Is this command now out of date?

**Comment by anthonydillon** [comment]
@allanford17 thank you very much for taking the time to report this to us. It has in fact always been the case. The command is only a quick way to ensure which version of Ubuntu you have installed. The message warning there are "No LSB modules are available." is due to a lack of lsb modules installed by default in Ubuntu.

If you would like to remove the notice you can run `sudo apt-get install lsb-core`.
