### ISSUE TITLE
Install the snap should use snapcraft.io badge/embed

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/multipass.run#74]
https://snapcraft.io/multipass should be linked via the embeddable card e.g. https://snapcraft.io/multipass/embedded?button=black

Seems this was added in #30 to fix #26  but regressed?

**Comment by anthonydillon** [comment]
The install was moved to just a section on the homepage and it was deemed the snapcraft badge was not to be used on the homepage. @cassiocassio any thoughts?

**Comment by matthewpaulthomas** [comment]
The Snap Store buttons make it easy to link to a snap, they provide more info about the snap, and they increase brand awareness of the Snap Store.

However, sometimes there are more important reasons to do something else. For example, [on microk8s.io](https://microk8s.io/#get-started) and [on microstack.io](https://microstack.run/#get-started) we provide CLI instructions instead, because that’s faster: installing the snap is step 1 and the following steps are in the CLI too.

Here, we used a standard button so that it would be consistent with the Windows and macOS buttons alongside. That isn’t necessarily an either/or choice, though. We could use a Snap Store button, and still look consistent, by using custom “Download for Windows” and “Download for macOS” buttons that were the same size.

**Comment by anthonydillon** [comment]
It sounds like this is not because anyone is against using the snapcraft badge but in this case consistency in the UI is more important as a comparison and method of highlighting the recommended option.

I will be close this issue but if you feel strongly and would like to continue the discuss please reopen and comment.
