### ISSUE TITLE
Use qemu backing file instead of directly using the image

### ISSUE THREAD

**Issue by Akilesh1597** [canonical-web-and-design/multipass.run#77]
From what I understand multipass provides an abstraction which is somewhere between virsh for kvm and docker for containers but lacks a lot of features from both . 

One good feature to have is provision to using a local image store similar to docker and the VM would use a backing file instead of directly using images from the store. 

There should be abstractions for snapshoting VMs to create new images similar to the docker image layers . Publishing images to local / remote image stores . This would provide users an ecosystem for developing and sharing apps. 

# qemu-img info  /var/snap/multipass/common/data/multipassd/vault/instances/thiru-test/ubuntu-18.04-server-cloudimg-amd64.img 
image: /var/snap/multipass/common/data/multipassd/vault/instances/thiru-test/ubuntu-18.04-server-cloudimg-amd64.img
file format: qcow2
virtual size: 5.0G (5368709120 bytes)
disk size: 475M
cluster_size: 65536
Format specific information:
    compat: 0.10
    refcount bits: 16

**Comment by matthewpaulthomas** [comment]
@Akilesh1597 Hi, this looks to be an issue with Multipass itself, rather than the multipass.run Web site. (I just realised we don’t have an obvious link for reporting issues with Multipass itself. [We’ll fix that.](https://github.com/canonical-web-and-design/multipass.run/issues/78))

The repo for Multipass itself is [canonical/multipass](https://github.com/canonical/multipass/issues). I can’t move this issue there because it’s in a different GitHub organisation. (Long story…) So if it isn’t already covered in their open issues, please report it there instead. Thanks.
